[build]
command = "npm run build"
functions = "functions"
publish = "dist"

[dev]
autoLaunch = false
command = "npm run dev:webpack"
framework = "#custom"
port = 8080
publish = "dist"
targetPort = 8079
